"""category_model_change

Revision ID: 406acbbe99f5
Revises: 8b88c4fe1a2b
Create Date: 2025-09-08 17:54:54.988292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406acbbe99f5'
down_revision: Union[str, Sequence[str], None] = '8b88c4fe1a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_items',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'item_id')
    )
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    op.drop_constraint(op.f('items_category_id_fkey'), 'items', type_='foreignkey')
    op.drop_column('items', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('items_category_id_fkey'), 'items', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    op.drop_table('category_items')
    # ### end Alembic commands ###
