"""user_vendor_relationship

Revision ID: 517e73e878b6
Revises: fa8e8d36bd92
Create Date: 2025-09-06 17:14:18.542999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517e73e878b6'
down_revision: Union[str, Sequence[str], None] = 'fa8e8d36bd92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'vendors', ['user_id'])
    op.create_foreign_key(None, 'vendors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='foreignkey')
    op.drop_constraint(None, 'vendors', type_='unique')
    op.drop_column('vendors', 'user_id')
    # ### end Alembic commands ###
