"""category_item_mapping_change

Revision ID: 8b88c4fe1a2b
Revises: e8668651c932
Create Date: 2025-09-08 12:33:10.245273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b88c4fe1a2b'
down_revision: Union[str, Sequence[str], None] = 'e8668651c932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_items')
    op.add_column('categories', sa.Column('vendor_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_categories_vendor_id'), 'categories', ['vendor_id'], unique=False)
    op.create_foreign_key(None, 'categories', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.add_column('items', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    op.create_foreign_key(None, 'items', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    op.drop_column('items', 'category_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_vendor_id'), table_name='categories')
    op.drop_column('categories', 'vendor_id')
    op.create_table('category_items',
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('category_items_category_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('category_items_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'item_id', name=op.f('category_items_pkey'))
    )
    # ### end Alembic commands ###
